// <auto-generated />
using System;
using FirsatBul.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace FirsatBul.DataAccess.Migrations.FirsatBulDb
{
    [DbContext(typeof(FirsatBulDbContext))]
    [Migration("20210327122208_entityInitial-mig")]
    partial class entityInitialmig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("FirsatBul.Entities.Firsatlar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FirsatExpirationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FirsatName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Firsatlar");
                });
#pragma warning restore 612, 618
        }
    }
}
